version: 2.1

orbs:
  slack: circleci/slack@volatile

executors:
  cli:
    docker:
      - image: circleci/circleci-cli:latest

workflows:
  validate-test-deploy:
    jobs:
      - lint

      - validate:
          requires:
            - lint

      - notifytest:
          requires:
            - validate
          context: orb-publishing

      - statustestpass:
          requires:
            - validate
          context: orb-publishing

      - publish-dev:
          requires:
            - notifytest
            - statustestpass
          context: orb-publishing

      - promote-prod:
          requires:
            - publish-dev
          filters:
            branches:
              only: master
          context: orb-publishing

jobs:
  lint:
    docker:
      - image: singapore/lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout
      - run: circleci orb validate src/@orb.yml

  notifytest:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - slack/notify:
          message: "UserID mentioning is the only valid form. link_names still works but is depricated. <!subteam^SEBESSETS> <!subteam^SEBESSETS|orbs>"
          color: "#f4aa42"
          mentions: ""

  statustestpass:
    docker:
      - image: circleci/node
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - slack/status:
          mentions: ""

  statustestfail:
    docker:
      - image: circleci/node
    steps:
      - run: exit 1 #toggle this to force success or status for testing
      - slack/status:
          mentions: ""

  publish-dev:
    executor: cli
    steps:
      - checkout
      - run: circleci orb publish src/@orb.yml circleci/slack@dev:$CIRCLE_BRANCH-$CIRCLE_SHA1 --token $CIRCLE_TOKEN

  promote-prod:
    executor: cli
    steps:
      - checkout
      - run: circleci orb publish promote circleci/slack@dev:$CIRCLE_BRANCH-$CIRCLE_SHA1 patch --token $CIRCLE_TOKEN
